/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './app.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/forms/src/directives/default_value_accessor';
import * as import13 from '@angular/forms/src/directives/control_value_accessor';
import * as import14 from '@angular/forms/src/directives/ng_model';
import * as import15 from '@angular/forms/src/directives/ng_control';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/security';
const nodeDebugInfos_HelloWorldComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.HelloWorldComponent],import1.HelloWorldComponent,{})];
var renderType_HelloWorldComponent_Host:import2.RenderComponentType = (null as any);
class _View_HelloWorldComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _HelloWorldComponent_0_4:import1.HelloWorldComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_HelloWorldComponent_Host0,renderType_HelloWorldComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_HelloWorldComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hello-world-app',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HelloWorldComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HelloWorldComponent_0_4 = new import1.HelloWorldComponent(this.parentInjector.get(import9.DomSanitizer));
    this._appEl_0.initComponent(this._HelloWorldComponent_0_4,[],compView_0);
    compView_0.create(this._HelloWorldComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.HelloWorldComponent) && (0 === requestNodeIndex))) { return this._HelloWorldComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HelloWorldComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_HelloWorldComponent_Host === (null as any))) { (renderType_HelloWorldComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_HelloWorldComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HelloWorldComponentNgFactory:import11.ComponentFactory<import1.HelloWorldComponent> = new import11.ComponentFactory<import1.HelloWorldComponent>('hello-world-app',viewFactory_HelloWorldComponent_Host0,import1.HelloWorldComponent);
const styles_HelloWorldComponent:any[] = [];
const nodeDebugInfos_HelloWorldComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import12.DefaultValueAccessor,
    import13.NG_VALUE_ACCESSOR,
    import14.NgModel,
    import15.NgControl,
    import16.NgControlStatus
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import17.TemplateRef,
    import18.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_HelloWorldComponent:import2.RenderComponentType = (null as any);
class _View_HelloWorldComponent0 extends import3.DebugAppView<import1.HelloWorldComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _DefaultValueAccessor_3_3:import12.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_3_4:any[];
  _NgModel_3_5:import14.NgModel;
  _NgControl_3_6:any;
  _NgControlStatus_3_7:import16.NgControlStatus;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import4.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import18.NgIf;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_HelloWorldComponent0,renderType_HelloWorldComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_HelloWorldComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,0,4));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',this.debug(2,0,18));
    this._el_3 = this.renderer.createElement(parentRenderNode,'textarea',this.debug(3,1,0));
    this.renderer.setElementAttribute(this._el_3,'placeholder','paste data here');
    this.renderer.setElementAttribute(this._el_3,'style','width: 100%; height: 200px;');
    this._DefaultValueAccessor_3_3 = new import12.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_3));
    this._NG_VALUE_ACCESSOR_3_4 = [this._DefaultValueAccessor_3_3];
    this._NgModel_3_5 = new import14.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_3_4);
    this._NgControl_3_6 = this._NgModel_3_5;
    this._NgControlStatus_3_7 = new import16.NgControlStatus(this._NgControl_3_6);
    this._el_4 = this.renderer.createElement(parentRenderNode,'br',this.debug(4,1,109));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',this.debug(5,1,113));
    this._anchor_6 = this.renderer.createTemplateAnchor(parentRenderNode,this.debug(6,2,0));
    this._appEl_6 = new import4.AppElement(6,(null as any),this,this._anchor_6);
    this._TemplateRef_6_5 = new import17.TemplateRef_(this._appEl_6,viewFactory_HelloWorldComponent1);
    this._NgIf_6_6 = new import18.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',this.debug(7,2,90));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_3,'ngModelChange',this.eventHandler(this._handle_ngModelChange_3_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_3,'input',this.eventHandler(this._handle_input_3_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_3,'blur',this.eventHandler(this._handle_blur_3_2.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_3_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_3_0.bind(this)));
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.DefaultValueAccessor) && (3 === requestNodeIndex))) { return this._DefaultValueAccessor_3_3; }
    if (((token === import13.NG_VALUE_ACCESSOR) && (3 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_3_4; }
    if (((token === import14.NgModel) && (3 === requestNodeIndex))) { return this._NgModel_3_5; }
    if (((token === import15.NgControl) && (3 === requestNodeIndex))) { return this._NgControl_3_6; }
    if (((token === import16.NgControlStatus) && (3 === requestNodeIndex))) { return this._NgControlStatus_3_7; }
    if (((token === import17.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import18.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(3,1,0);
    changes = (null as any);
    this.debug(3,1,10);
    const currVal_4:any = this.context.content;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_3_5.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_3_5.ngOnChanges(changes); }
    this.debug(6,2,3);
    const currVal_11:any = this.context.content;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_6_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(1,0,4);
    const currVal_0:any = import5.interpolate(1,'',this.context.title,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(3,1,0);
    const currVal_5:any = this._NgControlStatus_3_7.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_3,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.debug(3,1,0);
    const currVal_6:any = this._NgControlStatus_3_7.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_3,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.debug(3,1,0);
    const currVal_7:any = this._NgControlStatus_3_7.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_3,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.debug(3,1,0);
    const currVal_8:any = this._NgControlStatus_3_7.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_3,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.debug(3,1,0);
    const currVal_9:any = this._NgControlStatus_3_7.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_3,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.debug(3,1,0);
    const currVal_10:any = this._NgControlStatus_3_7.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_3,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(3,1,0);
    this._NgModel_3_5.ngOnDestroy();
  }
  private _handle_ngModelChange_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(3,1,10);
    const pd_0:any = ((<any>(this.context.content = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_3_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(3,1,0);
    const pd_0:any = ((<any>this._DefaultValueAccessor_3_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_3_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(3,1,0);
    const pd_0:any = ((<any>this._DefaultValueAccessor_3_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HelloWorldComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.HelloWorldComponent> {
  if ((renderType_HelloWorldComponent === (null as any))) { (renderType_HelloWorldComponent = viewUtils.createRenderComponentType('/home/viltsu/WebstormProjects/ynab2/app/app.component.html',0,import10.ViewEncapsulation.None,styles_HelloWorldComponent,{})); }
  return new _View_HelloWorldComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_HelloWorldComponent1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_HelloWorldComponent1 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_HelloWorldComponent1,renderType_HelloWorldComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_HelloWorldComponent1);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',this.debug(0,2,0));
    this.renderer.setElementAttribute(this._el_0,'download','tili.csv');
    this._text_1 = this.renderer.createText(this._el_0,'download',this.debug(1,2,78));
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(0,2,19);
    const currVal_1:any = this.parent.context.dataUrl;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,2,56);
    const pd_0:any = ((<any>this.parent.context.doDataUrl()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HelloWorldComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_HelloWorldComponent1(viewUtils,parentInjector,declarationEl);
}